export const images = {
  //our //

  group: require('../../assets/images/Group.png'),
  vector: require('../../assets/images/Vector.png'),

  // end 
  appLogo: require('../../assets/images/appLogo.png'),
  appLogo1: require('../../assets/images/appLogo1.png'),
  appBg: require('../../assets/images/appBg.png'),
  triskel_white: require('../../assets/images/triskel_white.png'),
  triskelAnim: require('../../assets/images/triskelAnim.json'),
  arrow_back: require('../../assets/images/arrow_back.png'),
  successAnim: require('../../assets/images/success.json'),
  setting_inactive: require('../../assets/images/Setting_l.png'),
  setting_inactiveNew: require('../../assets/images/setting_inactiveNew.png'),
  setting_activeNew: require('../../assets/images/setting_activeNew.png'),
  swap_inactive: require('../../assets/images/swap_inactive.png'),
  swap_inactive: require('../../assets/images/swap_inactive.png'),
  swap_inactiveNew: require('../../assets/images/swap_inactiveNew.png'),
  swap_activeNew: require('../../assets/images/Swap_activeNew.png'),
  dashboard_inactive: require('../../assets/images/dashboard_inactive.png'),
  dapp_inactive: require('../../assets/images/dapp_inactive.png'),
  otc_inactive: require('../../assets/images/Otc.png'),
  otc: require('../../assets/images/OtcActive.png'),
  dashboard_inactiveNew: require('../../assets/images/dashboardNew_inactive.png'),
  dashboard_activeNew: require('../../assets/images/DashboardNew_active.png'),
  triskelIcon: require('../../assets/images/triskelIcon.png'),
  Card: require('../../assets/images/Card.png'),
  security: require('../../assets/images/security.png'),
  aboutUs: require('../../assets/images/aboutUs.png'),
  Contact: require('../../assets/images/Contact.png'),
  alert: require('../../assets/images/alert.png'),
  currency: require('../../assets/images/currency.png'),
  policy: require('../../assets/images/policy.png'),
  right_arrow: require('../../assets/images/right-arrow-angle.png'),
  biometric_th: require('../../assets/images/biometric_th.png'),
  Lock: require('../../assets/images/padlock.png'),
  ToggleNew: require('../../assets/images/ic_toggleSwitch.png'),
  ToggleOff: require('../../assets/images/switch_off.png'),
  ToggleOff1: require('../../assets/images/switch_off1.png'),
  done: require('../../assets/images/done.png'),
  fav: require('../../assets/images/fav.png'),
  unfav: require('../../assets/images/unFav.png'),
  fav1: require('../../assets/images/fav1.png'),
  unfav1: require('../../assets/images/unfav1.png'),
  Scan: require('../../assets/images/ic_scan.png'),
  Scan1: require('../../assets/images/ic_scan1.png'),
  modal_top_line: require('../../assets/images/modal_topLine.png'),
  noContact: require('../../assets/images/noContact.png'),
  noContact1: require('../../assets/images/noContact1.png'),
  bin: require('../../assets/images/bin.png'),
  bin1: require('../../assets/images/bin1.png'),
  noPriceAlert: require('../../assets/images/noPriceAlert.png'),
  noPriceAlert1: require('../../assets/images/noPriceAlert1.png'),
  dapp_active: require('../../assets/images/dapp_active.png'),
  dashboard_active: require('../../assets/images/dashboard_active.png'),
  swap_active: require('../../assets/images/swap_active.png'),
  portfolio: require('../../assets/images/portfolio.png'),
  portfolioNew: require('../../assets/images/portfolioNew.png'),
  setting_active: require('../../assets/images/setting_active.png'),
  CancelIcon: require('../../assets/images/ic_cancel.png'),
  CancelIcon1: require('../../assets/images/ic_cancel1.png'),
  noti: require('../../assets/images/noti.png'),
  add: require('../../assets/images/add.png'),
  send: require('../../assets/images/call_made_black.png'),
  receive: require('../../assets/images/call_received_black.png'),
  PriceAlertIcon: require('../../assets/images/PriceAlertIcon.png'),
  PriceAlertIcon1: require('../../assets/images/PriceAlertIcon1.png'),
  searchNew: require('../../assets/images/searchNew.png'),
  searchNew1: require('../../assets/images/searchNew1.png'),
  HistoryIcon: require('../../assets/images/HistoryIcon.png'),
  HistoryIcon1: require('../../assets/images/HistoryIcon1.png'),
  ManageIconNew: require('../../assets/images/ManageIconNew.png'),
  ManageIconNew1: require('../../assets/images/ManageIconNew1.png'),
  graphLoss: require('../../assets/images/graphLoss.png'),
  graphSuccess: require('../../assets/images/graphSuccess.png'),
  loss: require('../../assets/images/loss.png'),
  gain: require('../../assets/images/gain.png'),
  copyNew: require('../../assets/images/copyNew.png'),
  Share: require('../../assets/images/share.png'),
  copyNew1: require('../../assets/images/copyNew1.png'),
  Share1: require('../../assets/images/ic_share1.png'),
  send_bg: require('../../assets/images/send_bg.png'),
  Swap_bg: require('../../assets/images/Swap_bg.png'),
  Swap_bg1: require('../../assets/images/Swap_bg1.png'),
  receive_bg: require('../../assets/images/receive_bg.png'),
  deposit: require('../../assets/images/deposit.png'),
  withdrawNew: require('../../assets/images/withdrawNew.png'),
  deposit1: require('../../assets/images/deposit1.png'),
  withdrawNew1: require('../../assets/images/withdrawNew1.png'),
  addressBook: require('../../assets/images/addressBook.png'),
  addressBook1: require('../../assets/images/addressBook1.png'),
  qrLogo: require('../../assets/images/qrLogo.png'),
  LogoWithBg: require('../../assets/images/LogoWithBg.png'),
  triskel_Splash: require('../../assets/images/data11.json'),// require('../../assets/images/triskel_Splash.json'),
  triskel_Splash_Dark: require('../../assets/images/dataNew.json'),
  portFolioNew: require('../../assets/images/portfolioNew.png'),
  colorCode1: require('../../assets/images/colorCode1.png'),
  colorCode2: require('../../assets/images/colorCode2.png'),
  colorCode3: require('../../assets/images/colorCode3.png'),
  csv: require('../../assets/images/csv.png'),
  filter: require('../../assets/images/filter.png'),
  calendar: require('../../assets/images/calendar.png'),
  alchemy: require('../../assets/images/alchemy.png'),
  loader: require('../../assets/images/Loader.json'),
  loaderDark: require('../../assets/images/LoaderDark.json'),
  bioMetric: require('../../assets/images/bioMetric.png'),
  clock: require('../../assets/images/clock.png'),
  walletManage: require('../../assets/images/walletManage.png'),
  walletManage1: require('../../assets/images/walletManage1.png'),
  newLoader: require('../../assets/images/data.json'),
  price_alert: require('../../assets/images/price_alert.png'),
  info: require('../../assets/images/info.png'),
  fb: require('../../assets/images/fb.png'),
  google: require('../../assets/images/google.png'),
  apple: require('../../assets/images/apple.png'),
  linkedIn: require('../../assets/images/linkedIn.png'),
  mail: require('../../assets/images/mail.png'),
  fb1: require('../../assets/images/fb1.png'),
  google1: require('../../assets/images/google1.png'),
  apple1: require('../../assets/images/apple1.png'),
  linkedIn1: require('../../assets/images/linkedIn1.png'),
  mail1: require('../../assets/images/mail1.png'),
  toggleGreen: require('../../assets/images/toggleGreen.png'),
  toggleGreen1: require('../../assets/images/toggleGreen1.png'),
  swapTxn: require('../../assets/images/swapTxn.png'),
  failTxn: require('../../assets/images/failTxn.png'),
  announcement: require('../../assets/images/announcements.png'),
  left_arrow: require('../../assets/images/left-arrow-angle.png'),
  infoIcon: require('../../assets/images/icon_info_phrase.png'),
  icon_delete: require('../../assets/images/icon_delete.png'),
  icon_delete1: require('../../assets/images/icon_delete1.png'),
  icon_default: require('../../assets/images/icon_default.png'),
  notiDot: require('../../assets/images/noti_dot.png'),
  tryAgain: require('../../assets/images/Untitled.png'),
  ArrowLong: require('../../assets/images/arrow_long.png'),
  ArrowLong1: require('../../assets/images/arrow_long1.png'),
  SearchWhite: require('../../assets/images/ic_search.png'),
  RightArrow: require('../../assets/images/ic_rightArrow.png'),
  dropdown: require('../../assets/images/dropdown.png'),
  reload: require('../../assets/images/reload.png'),
  s_light_nav_Active: require('../../assets/images/s_light_nav_Active.png'),
  s_light_nav: require('../../assets/images/s_light_nav.png'),
  Delete: require('../../assets/images/ic_del.png'),
  close_icon: require('../../assets/images/modal_close_icon.png'),
  completed: require('../../assets/images/complete.png'),
  DownArrow: require('../../assets/images/dropdown.png'),
  DownArrow1: require('../../assets/images/dropdown1.png'),
  wallet_backup: require('../../assets/images/wallet_backup.png'),
  reward: require('../../assets/images/reward.png'),
  ref: require('../../assets/images/ref.png'),
  price: require('../../assets/images/price.png'),
  gift: require('../../assets/images/gift.png'),
  PolygonGreen: require('../../assets/images/PolygonGreen.png'),
  Polygonbrown: require('../../assets/images/Polygonbrown.png'),
  PolygonOlive: require('../../assets/images/PolygonOlive.png'),
  PolygonSky: require('../../assets/images/PolygonSky.png'),
  PolygonOrange: require('../../assets/images/PolygonOrange.png'),
  cardFront: require('../../assets/images/cardFront.png'),
  cardBack: require('../../assets/images/cardBack.png'),
  cardCross: require('../../assets/images/cardCross.png'),
  recharge: require('../../assets/images/recharge.png'),
  // rightArrowNew:require('../../assets/images/rightArrowNew.png'),
  // dropDownNew:require('../../assets/images/dropDownNew.png'),
  // frontIdImg:require('../../assets/images/frontIdImg.png'),
  // selfieHoldingImg:require('../../assets/images/selfieHoldingImg.png'),
  // cancelIconNew:require('../../assets/images/cancelIconNew.png'),
  dropdownnew: require('../../assets/images/drop_new.png'),
  showQr: require('../../assets/images/showQr.png'),
  rightArrowNew: require('../../assets/images/rightArrowNew.png'),
  frontIdImg: require('../../assets/images/frontIdImg.png'),
  selfieHoldingImg: require('../../assets/images/selfieHoldingImg.png'),
  cancelIconNew: require('../../assets/images/cancelIconNew.png'),
  crossQr: require('../../assets/images/crossQr.png'),
  dummyQr: require('../../assets/images/dummyQr.png'),
  teher: require('../../assets/images/teher.png'),
  color_arrow: require('../../assets/images/color_arrow.png'),
  color_arrowb: require('../../assets/images/color_arrowb.png'),
  copydeposit: require('../../assets/images/copydeposit.png'),
  sendOutlined: require('../../assets/images/sendOutlined.png'),
  review: require("../../assets/images/Review.json"),
  review1: require("../../assets/images/Review1.json"),
  polygonBlack: require("../../assets/images/PolygonBlack.png"),
  rejectedJson: require("../../assets/images/rejected.json"),
  cardBackwhiteStrip: require("../../assets/images/cardBackWhiteStrip.png"),
  hide: require("../../assets/images/hide.png"),
  view: require("../../assets/images/view.png"),
  cardFrontWithSim: require("../../assets/images/cardFrontWithoutSim.png"),
  coinUSD: require("../../assets/images/coinUSD.png"),
  coinEUR: require("../../assets/images/coinEUR.png"),
  unfavbm: require("../../assets/images/ic_bookmark.png"),
  favbm: require("../../assets/images/ic_save_bookmark.png"),
  radio_active: require("../../assets/images/radio_icon_active.png"),
  radio_inactive: require("../../assets/images/radio_icon_default.png"),
  transakLogo: require("../../assets/images/transakLogo.png"),
  contactUs: require("../../assets/images/contactUs.png"),
  icon_help: require("../../assets/images/icon_help.png"),
  image_camera: require("../../assets/images/image_camera.png"),
  image_gallery: require("../../assets/images/image_gallery.png"),
  USPreferdCardBlack: require("../../assets/images/USPreferedCardBlack.png"),
  USPreferdCardBlackBack: require("../../assets/images/USPreferedCardBlackBack.png"),
  radioButton: require("../../assets/images/radioButton.png"),
  language: require("../../assets/images/world.png"),
  spain: require("../../assets/images/spain.png"),
  unitedKingdom: require("../../assets/images/unitedkingdom.png"),
  ref1: require("../../assets/images/ref1.png"),
  refImg: require("../../assets/images/refImg.png"),
  referrals: require("../../assets/images/referrals.png"),
  referral1: require("../../assets/images/referral1.png"),
  road: require("../../assets/images/road.png"),
  roadinactive: require("../../assets/images/roadinactive.png"),
  road1: require("../../assets/images/road1.png"),
  roadinactive1: require("../../assets/images/roadinactive1.png"),
  franchise: require("../../assets/images/franchise.png"),
  theme: require("../../assets/images/Theme.png"),
  light: require("../../assets/images/light.png"),
  dark: require("../../assets/images/dark.png"),
  welcomelogo: require("../../assets/images/main_WelcomeLogo.png"),
  safeIcon: require("../../assets/images/safeIcon.png"),
  checked: require("../../assets/images/checked.png"),
  blackBack: require("../../assets/images/blackBack.png"),
  forwardIcon: require("../../assets/images/forwardIcon.png"),
  paste: require("../../assets/images/paste.png"),
  alertsecret: require("../../assets/images/alertsecret.png"),
  bullet: require("../../assets/images/bullet.png"),
  smallAlert: require("../../assets/images/smallAlert.png"),
  manageFutureLogo: require("../../assets/images/manageFutureLogo.png"),
  infoIcon: require("../../assets/images/infoIcon.png"),
  deleteIcon: require("../../assets/images/deleteIcon.png"),
  eth: require("../../assets/images/Eth.png"),
  bnb: require("../../assets/images/BNB.png"),
  btc: require("../../assets/images/BTC.png"),
  tron: require("../../assets/images/Tron.png"),
  copyNewblack: require("../../assets/images/CopyNewblack.png"),
  manageWallet: require("../../assets/images/manageWallets.png"),
  preferences: require("../../assets/images/preferences.png"),
  referalAndRewards: require("../../assets/images/referalAndRewards.png"),
  privacyPolicy: require("../../assets/images/PrivacyPolicy.png"),
  prePaidCards: require("../../assets/images/PrepPaidCards.png"),
  faceBook: require("../../assets/images/Facebook.png"),
  instagram: require("../../assets/images/instagram.png"),
  telegram: require("../../assets/images/Telegram.png"),
  futureWallet: require("../../assets/images/FutureWallet.png"),
  logOut: require("../../assets/images/LogOut.png"),
  nativeCurrency: require("../../assets/images/nativeCurrency.png"),
  setAmount: require("../../assets/images/setAmount.png"),
  copyColored: require("../../assets/images/copyColored.png"),
  providerIcon: require("../../assets/images/providerIcon.png"),
  greaterthan:require("../../assets/images/greater_than.png"),
  headerIcon:require("../../assets/images/VectorLess.png"),

  // notification

  notification1:require("../../assets/images/notificationImg1.png"),
  notification2:require("../../assets/images/notificationImg2.png"),
  notification3:require("../../assets/images/notificationImg3.png"),

  // mainpage
  bell:require("../../assets/images/Bell.png"),
  MinimizeSquare:require("../../assets/images/MinimizeSquare.png"),
  RecieveSquare:require("../../assets/images/ReciveSquare.png"),
  sell:require("../../assets/images/sell.png"),
  send:require("../../assets/images/send.png"),  
  mainTokenImg1:require("../../assets/images/mainTokenImg1.png"),
  mainTokenImg2:require("../../assets/images/mainTokenImg2.png"),
  mainTokenImg3:require("../../assets/images/mainTokenImg3.png"),
  mainTokenImg4:require("../../assets/images/mainTokenImg4.png"),  
  bar:require("../../assets/images/bar.png"),
  dashboard:require("../../assets/images/dashboard.png"),  
  portfolioTab:require("../../assets/images/portfolioTab.png"),  
  dapp:require("../../assets/images/dapp.png"),  
  swap:require("../../assets/images/swap.png"),  
  setting:require("../../assets/images/setting.png"),  
  //Passcode
  biometric_Blue:require("../../assets/images/bioMetric_blue.png"),

  // buy&sell
  usd:require("../../assets/images/usd.png"),
  whiteTriangle:require("../../assets/images/whiteTriangle.png"),
  deleteLogo:require("../../assets/images/deleteLogo.png"),
  DangerCircle:require("../../assets/images/DangerCircle.png"),
  settingGreater:require("../../assets/images/settingGreater.png"),
  swapBitcoin:require("../../assets/images/swapBitcoin.png"),
  transferBitcoin:require("../../assets/images/transferBitcoin.png"),
  topTransferBitcoin:require("../../assets/images/topTransferBitcoin.png"),
  downTransferBitcoin:require("../../assets/images/downTransferBitcoin.png"),
  smartContact:require("../../assets/images/smartContact.png"),

  dappLogo:require("../../assets/images/dappLogo.png"),
  compoundLogo:require("../../assets/images/compound-comp-logo.png"),
  rightBlueArrow:require("../../assets/images/rightBlueArrow.png"),


  // .......................... setting ............................//
  blueManageWallet:require("../../assets/images/blueManageWallet.png"),
  blueSecurity:require("../../assets/images/blueSecurity.png"),
  bluePrepaidCards:require("../../assets/images/bluePrepaidCards.png"),
  blueNativeCurrency:require("../../assets/images/blueNativeCurrency.png"),
  blueAddressBook:require("../../assets/images/blueAddressBook.png"),
  blueFutureWallet:require("../../assets/images/blueFutureWallet.png"),
  bluePreferences:require("../../assets/images/bluePreferences.png"),
  bluePrivacyPolicy:require("../../assets/images/bluePrivacyPolicy.png"),
  blueRewards:require("../../assets/images/blueRewards.png"),
  blueTelegram:require("../../assets/images/blueTelegram.png"),
  blueFacebook:require("../../assets/images/blueFacebook.png"),
  blueInstagram:require("../../assets/images/blueInstagram.png"),
  blueContactUs:require("../../assets/images/blueContactUs.png"),
  blueAboutUs:require("../../assets/images/blueAboutUs.png"),
  blueLogout:require("../../assets/images/blueLogout.png"),


  // **************************dark theme****************// 
  groupdrk:require("../../assets/images/GroupDrk.png"),

};


// export default images;
